package com.github.adamantcheese.chan.core.site.common

object ISO_3166_1_ALPHA_2_FLAGS {
    val FLAG_CODES = mutableMapOf(Pair("AD","Andorra"),
            Pair("AE","United Arab Emirates"),
            Pair("AF","Afghanistan"),
            Pair("AG","Antigua and Barbuda"),
            Pair("AI","Anguilla"),
            Pair("AL","Albania"),
            Pair("AM","Armenia"),
            Pair("AO","Angola"),
            Pair("AQ","Antarctica"),
            Pair("AR","Argentina"),
            Pair("AS","American Samoa"),
            Pair("AT","Austria"),
            Pair("AU","Australia"),
            Pair("AW","Aruba"),
            Pair("AX","Åland Islands"),
            Pair("AZ","Azerbaijan"),
            Pair("BA","Bosnia and Herzegovina"),
            Pair("BB","Barbados"),
            Pair("BD","Bangladesh"),
            Pair("BE","Belgium"),
            Pair("BF","Burkina Faso"),
            Pair("BG","Bulgaria"),
            Pair("BH","Bahrain"),
            Pair("BI","Burundi"),
            Pair("BJ","Benin"),
            Pair("BL","Saint Barthélemy"),
            Pair("BM","Bermuda"),
            Pair("BN","Brunei Darussalam"),
            Pair("BO","Bolivia"),
            Pair("BQ","Bonaire"),
            Pair("BR","Brazil"),
            Pair("BS","Bahamas"),
            Pair("BT","Bhutan"),
            Pair("BV","Bouvet Island"),
            Pair("BW","Botswana"),
            Pair("BY","Belarus"),
            Pair("BZ","Belize"),
            Pair("CA","Canada"),
            Pair("CC","Cocos (Keeling) Islands"),
            Pair("CD","Congo"),
            Pair("CF","Central African Republic"),
            Pair("CG","Congo"),
            Pair("CH","Switzerland"),
            Pair("CI","Ivory Coast"),
            Pair("CK","Cook Islands"),
            Pair("CL","Chile"),
            Pair("CM","Cameroon"),
            Pair("CN","China"),
            Pair("CO","Colombia"),
            Pair("CR","Costa Rica"),
            Pair("CU","Cuba"),
            Pair("CV","Cape Verde Islands"),
            Pair("CW","Curaçao"),
            Pair("CX","Christmas Island"),
            Pair("CY","Cyprus"),
            Pair("CZ","Czechia"),
            Pair("DE","Germany"),
            Pair("DJ","Djibouti"),
            Pair("DK","Denmark"),
            Pair("DM","Dominica"),
            Pair("DO","Dominican Republic"),
            Pair("DZ","Algeria"),
            Pair("EC","Ecuador"),
            Pair("EE","Estonia"),
            Pair("EG","Egypt"),
            Pair("EH","Western Sahara"),
            Pair("ER","Eritrea"),
            Pair("ES","Spain"),
            Pair("ET","Ethiopia"),
            Pair("FI","Finland"),
            Pair("FJ","Fiji"),
            Pair("FK","Falkland Islands"),
            Pair("FM","Micronesia"),
            Pair("FO","Faroe Islands"),
            Pair("FR","France"),
            Pair("GA","Gabon"),
            Pair("GB","Great Britain"),
            Pair("GD","Grenada"),
            Pair("GE","Georgia"),
            Pair("GF","French Guiana"),
            Pair("GG","Guernsey"),
            Pair("GH","Ghana"),
            Pair("GI","Gibraltar"),
            Pair("GL","Greenland"),
            Pair("GM","Gambia"),
            Pair("GN","Guinea"),
            Pair("GP","Guadeloupe"),
            Pair("GQ","Equatorial Guinea"),
            Pair("GR","Greece"),
            Pair("GS","South Georgia"),
            Pair("GT","Guatemala"),
            Pair("GU","Guam"),
            Pair("GW","Guinea-Bissau"),
            Pair("GY","Guyana"),
            Pair("HK","Hong Kong"),
            Pair("HM","Heard Island"),
            Pair("HN","Honduras"),
            Pair("HR","Croatia"),
            Pair("HT","Haiti"),
            Pair("HU","Hungary"),
            Pair("ID","Indonesia"),
            Pair("IE","Ireland"),
            Pair("IL","Israel"),
            Pair("IM","Isle of Man"),
            Pair("IN","India"),
            Pair("IO","British Indian Ocean Territory"),
            Pair("IQ","Iraq"),
            Pair("IR","Iran"),
            Pair("IS","Iceland"),
            Pair("IT","Italy"),
            Pair("JE","Jersey"),
            Pair("JM","Jamaica"),
            Pair("JO","Jordan"),
            Pair("JP","Japan"),
            Pair("KE","Kenya"),
            Pair("KG","Kyrgyzstan"),
            Pair("KH","Cambodia"),
            Pair("KI","Kiribati"),
            Pair("KM","Comoros"),
            Pair("KN","Saint Kitts and Nevis"),
            Pair("KP","North Korea"),
            Pair("KR","South Korea"),
            Pair("KW","Kuwait"),
            Pair("KY","Cayman Islands"),
            Pair("KZ","Kazakhstan"),
            Pair("LA","Laos"),
            Pair("LB","Lebanon"),
            Pair("LC","Saint Lucia"),
            Pair("LI","Liechtenstein"),
            Pair("LK","Sri Lanka"),
            Pair("LR","Liberia"),
            Pair("LS","Lesotho"),
            Pair("LT","Lithuania"),
            Pair("LU","Luxembourg"),
            Pair("LV","Latvia"),
            Pair("LY","Libya"),
            Pair("MA","Morocco"),
            Pair("MC","Monaco"),
            Pair("MD","Moldova"),
            Pair("ME","Montenegro"),
            Pair("MF","Saint Martin"),
            Pair("MG","Madagascar"),
            Pair("MH","Marshall Islands"),
            Pair("MK","North Macedonia"),
            Pair("ML","Mali"),
            Pair("MM","Myanmar"),
            Pair("MN","Mongolia"),
            Pair("MO","Macao"),
            Pair("MP","Northern Mariana Islands"),
            Pair("MQ","Martinique"),
            Pair("MR","Mauritania"),
            Pair("MS","Montserrat"),
            Pair("MT","Malta"),
            Pair("MU","Mauritius"),
            Pair("MV","Maldives"),
            Pair("MW","Malawi"),
            Pair("MX","Mexico"),
            Pair("MY","Malaysia"),
            Pair("MZ","Mozambique"),
            Pair("NA","Namibia"),
            Pair("NC","New Caledonia"),
            Pair("NE","Niger"),
            Pair("NF","Norfolk Island"),
            Pair("NG","Nigeria"),
            Pair("NI","Nicaragua"),
            Pair("NL","Netherlands"),
            Pair("NO","Norway"),
            Pair("NP","Nepal"),
            Pair("NR","Nauru"),
            Pair("NU","Niue"),
            Pair("NZ","New Zealand"),
            Pair("OM","Oman"),
            Pair("PA","Panama"),
            Pair("PE","Peru"),
            Pair("PF","French Polynesia"),
            Pair("PG","Papua New Guinea"),
            Pair("PH","Philippines"),
            Pair("PK","Pakistan"),
            Pair("PL","Poland"),
            Pair("PM","Saint Pierre and Miquelon"),
            Pair("PN","Pitcairn"),
            Pair("PR","Puerto Rico"),
            Pair("PS","Palestine"),
            Pair("PT","Portugal"),
            Pair("PW","Palau"),
            Pair("PY","Paraguay"),
            Pair("QA","Qatar"),
            Pair("RE","Réunion"),
            Pair("RO","Romania"),
            Pair("RS","Serbia"),
            Pair("RU","Russia"),
            Pair("RW","Rwanda"),
            Pair("SA","Saudi Arabia"),
            Pair("SB","Solomon Islands"),
            Pair("SC","Seychelles"),
            Pair("SD","Sudan"),
            Pair("SE","Sweden"),
            Pair("SG","Singapore"),
            Pair("SH","Saint Helena"),
            Pair("SI","Slovenia"),
            Pair("SJ","Svalbard and Jan Mayen"),
            Pair("SK","Slovakia"),
            Pair("SL","Sierra Leone"),
            Pair("SM","San Marino"),
            Pair("SN","Senegal"),
            Pair("SO","Somalia"),
            Pair("SR","Suriname"),
            Pair("SS","South Sudan"),
            Pair("ST","Sao Tome and Principe"),
            Pair("SV","El Salvador"),
            Pair("SX","Sint Maarten"),
            Pair("SY","Syria"),
            Pair("SZ","Eswatini"),
            Pair("TC","Turks and Caicos Islands"),
            Pair("TD","Chad"),
            Pair("TF","French Southern Territories"),
            Pair("TG","Togo"),
            Pair("TH","Thailand"),
            Pair("TJ","Tajikistan"),
            Pair("TK","Tokelau"),
            Pair("TL","Timor-Leste"),
            Pair("TM","Turkmenistan"),
            Pair("TN","Tunisia"),
            Pair("TO","Tonga"),
            Pair("TR","Turkey"),
            Pair("TT","Trinidad and Tobago"),
            Pair("TV","Tuvalu"),
            Pair("TW","Taiwan"),
            Pair("TZ","Tanzania"),
            Pair("UA","Ukraine"),
            Pair("UG","Uganda"),
            Pair("UM","United States Minor Outlying Islands"),
            Pair("US","United States of America"),
            Pair("UY","Uruguay"),
            Pair("UZ","Uzbekistan"),
            Pair("VA","Holy See"),
            Pair("VC","Saint Vincent and the Grenadines"),
            Pair("VE","Venezuela"),
            Pair("VG","Virgin Islands (British)"),
            Pair("VI","Virgin Islands (U.S.)"),
            Pair("VN","Vietnam"),
            Pair("VU","Vanuatu"),
            Pair("WF","Wallis and Futuna"),
            Pair("WS","Samoa"),
            Pair("YE","Yemen"),
            Pair("YT","Mayotte"),
            Pair("ZA","South Africa"),
            Pair("ZM","Zambia"),
            Pair("ZW","Zimbabwe"))
}