package com.github.adamantcheese.chan.features.embedding;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.github.adamantcheese.chan.core.model.PostImage;

public class EmbedResult {
    /**
     * The title for this embed result. While this can't be null, also don't make this an empty string either.
     */
    public String title;

    /**
     * An optional duration for this embed. If null and duration parsing is enabled, then another request will be sent to get a duration.
     * If you don't want/have any duration data, set this to an empty string.
     */
    public String duration;

    /**
     * An optional post image that is generated by an embedder, if image hotlinking is enabled. Makes some embeds more easily viewable in-app quickly.
     */
    public PostImage extraImage;

    @SuppressWarnings("unused")
    private EmbedResult() {} // for gson, don't use otherwise

    public EmbedResult(@NonNull String title, @Nullable String duration, @Nullable PostImage extraImage) {
        this.title = title;
        this.duration = duration;
        this.extraImage = extraImage;
    }
}
